server {
    listen       80;
    server_name  _;
    root         /usr/share/nginx/html;
    index        index.html;

    # SPA — tüm rotalar index.html'e
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Statik dosyalar için cache
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|mp3|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
    gzip_min_length 1024;
}